name: Deploy Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: |
          cd functions
          npm install
          
      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest
          
      - name: Set Firebase Config
        env:
          PPURIO_USER_ID: ${{ secrets.PPURIO_USER_ID }}
          PPURIO_API_KEY: ${{ secrets.PPURIO_API_KEY }}
        run: |
          firebase functions:config:set ppurio.userid="$PPURIO_USER_ID" ppurio.apikey="$PPURIO_API_KEY" --project attendance-check-system
          
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --only functions --token "$FIREBASE_TOKEN" --project attendance-check-system
