name: Deploy Firebase Functions
on:
  push:
    paths:
      - 'functions/**'
      - '.github/workflows/firebase-functions.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # v3 -> v4로 업데이트
        
      - name: Setup Node.js
        uses: actions/setup-node@v4  # v3 -> v4로 업데이트
        with:
          node-version: '18'
          cache: 'npm'  # npm 캐싱 추가
          cache-dependency-path: functions/package-lock.json
          
      - name: Install dependencies
        run: cd functions && npm ci  # npm install -> npm ci로 변경
        
      - name: Deploy to Firebase
        run: npx firebase-tools deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
